#ifndef common_1LKrZ2oprBaT
#define common_1LKrZ2oprBaT



#include <string.h>
#include <err.h>
#include "avl_tree.h"
#include <sys/types.h>
#include <stdlib.h>



// this is not assert: not intended to be disabled in non-debug mode
#define ERRIF(c) do {                                             \
        if (c)                                                    \
            err(1, #c " at " __FILE__ ":%d because", __LINE__);   \
    } while (0)

#define NOT_IMPLEMENTED errx(1, "NOT IMPLEMENTED " __FILE__ ":%d", __LINE__)



#define min(x, y) ((x) < (y) ? (x) : (y))

#define max(x, y) ((x) > (y) ? (x) : (y))



void *_new(size_t size);

#define new(ty) _new(sizeof(ty))

#define zero(ptr) memset(ptr, 0, sizeof(*ptr))



#define STACK(ty) struct { size_t alloc, used; ty *array; }

#define ALLOCATE(foo, s) do {                                   \
        foo.alloc = s;                                          \
        foo.used = 0;                                           \
        foo.array = malloc(foo.alloc * sizeof(*foo.array));     \
        ERRIF(!foo.array);                                      \
    } while (0)

#define ENOUGH(foo) do {                                                \
        if (foo.used >= foo.alloc) {                                    \
            foo.alloc *= 2;                                             \
            foo.array = realloc(foo.array, foo.alloc * sizeof(*foo.array)); \
            ERRIF(!foo.array);                                          \
        }                                                               \
    } while (0)

#define TRIM(foo) do {                                                  \
        foo.alloc = foo.used;                                           \
        foo.array = realloc(foo.array, foo.alloc * sizeof(*foo.array)); \
        ERRIF(!foo.array);                                              \
    } while (0)

#define PUSH(foo, val) (foo.array[foo.used++] = (val))

#define POP(foo) (foo.array[--foo.used])

#define AT(foo, idx) (foo.array[idx])



struct file {
    ssize_t size; // -1: unknown from config file. <-1: factor of source size.
    mode_t mode; // 07000000: unknown from config file.
    nlink_t nlink;
    time_t atime, mtime, ctime; // -1: unknown from config file.
    char *srcName; // NULL: generated by algo indicated by srcSize
    ssize_t srcSize; // -1: unknown from config file.
};

/* New file records are initialisedfrom here.  Values not set by the
   user may be retrieved from the file system, or be made up. */
extern struct file uninitFile;



struct parseResult {
    STACK(struct file *) files;
    avl_Tree names;
};



enum { algoRoot, algoIntegers, algoChars };

extern const char *algorithms[];

#endif
