#ifndef parser_RlBM2GiE1tuq
#define parser_RlBM2GiE1tuq

#include "avl_tree.h"
#include "macros.h"
#include <sys/types.h>
#include <stdlib.h>

struct file {
    ssize_t size; // -1: unknown from config file. <-1: factor of source size.
    mode_t mode; // 07000000: unknown from config file.
    nlink_t nlink;
    time_t atime, mtime; // -1: unknown from config file.
    char *srcName; // NULL: generated by algo indicated by srcSize
    ssize_t srcSize; // -1: unknown from config file.
};

struct file uninitFile;

struct parseResult {
    STACK(struct file *) files;
    avl_Tree names;
};

int parse(struct parseResult *parseResult, int fd);

#endif
