#!/bin/bash
set -u -e -C;
shopt -s nullglob;

function err { echo $'\e[1;31m'"$@"$'\e[m'; exit 1; }
function warn { echo $'\e[1;35m'"$@"$'\e[m'; }
function info { echo $'\e[36m'"$@"$'\e[m'; }

function ask_yN {
    local answer='';
    read -n 1 -s -p $'\e[34m'"$* [yN]"$'\e[m' answer;
    if test "${answer}" = y; then
        info yes;
        return 0;
    fi;
    info no;
    return 1;
}

dir=testdir

fusermount -u "$dir" 2>/dev/null || true
mkdir -p "$dir"

#dd if=/dev/urandom of="${dir}/template" bs=1k count=10
cp mnt/template "$dir"
os="$(stat -c%s "${dir}/template")";

cat <<EOF >|"${dir}/otffsrc"
original : pass template
EOF

function size {
    echo "\"size-${1}\" : pass template, size ${1}" >>"${dir}/otffsrc";
}
size $((RANDOM % 1024))
size $((RANDOM % os))
for i in '' k M G T P; do
    size "$((RANDOM % 1000))${i}";
done;
for i in ki Mi Gi Ti Pi; do
    size "$((RANDOM % 1024))${i}";
done;
size "$((RANDOM % 100000))x";

info "mounting otffs on $dir"
./otffs "$dir" 2>| "${dir}/log"&
until test -e "${dir}/original"; do sleep 0.1; done

info "running tests"

echo simple pass
cmp mnt/template "${dir}/original"

for f in "${dir}/"*; do
    fs="$(stat -c%s "$f")";
    if test "$fs" -le "$os"; then
        echo "short $f"
        dd status=none iflag=count_bytes count="$fs" if="${dir}/original" | cmp - "$f"
    elif test "$fs" -le "$((250 << 20))"; then
        echo "medium $f"
        ./cmprep "${dir}/original" "$f"
    else
        for i in {1..10}; do
            off="$(shuf -n1 -i0-"$((fs - os))")"
            echo "huge $f $off..$((off + os - 1))"
            test "$((off + os))" -lt "$fs" || err 'xcrZLRPxcKKA'
            s=$((off % os))
            cmp \
                <(dd status=none iflag=skip_bytes,count_bytes skip="$off" count="$os" \
                     if="${f}") \
                <(dd status=none iflag=skip_bytes  skip="$s"  if="${dir}/original";
                  dd status=none iflag=count_bytes count="$s" if="${dir}/original"
                 );
        done;
    fi
done

fusermount -u "$dir";
